### ISSUE TITLE
Incomplete overlap when switching between dark and light modes

### ISSUE THREAD

**Issue by JerryZhangZZY** [EvanNotFound/typora-theme-redefine#2]
Content will be misaligned up and down

**Comment by EvanNotFound** [comment]
please provide screenshots

**Comment by JerryZhangZZY** [comment]
The following html code can cause such problem:
<center><b><font size ='2'>Figure 1. shape design</font></b></center></font>

**Comment by JerryZhangZZY** [comment]
I think that's clear enough
<img width="300" alt="截屏2023-04-25 下午3 53 12" src="https://user-images.githubusercontent.com/57243821/234211129-1e169e75-a7b0-47be-b720-9cc41a5e0005.png"><img width="300" alt="截屏2023-04-25 下午3 53 20" src="https://user-images.githubusercontent.com/57243821/234211149-f9a7040d-17be-4f4d-81c0-f5023c98deef.png">

**Comment by JerryZhangZZY** [comment]
To solve it, simply add the following codes to **_redefine-light.css_**

```css
html,
body {
  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
  background: #202124;
  background: var(--background-color);
  fill: currentColor;
  line-height: 1.625rem;
}
```

I think you might have accidentally lost it : )
